### PR TITLE
Fixing output printer - newest behat version use Output Factories

### PR DESCRIPTION
**Pull request by vmztr**
Behat 3.1.0 started using OutputFactories, if someone tries to use BEX with newest behat this results in error because BEX is still using OutputPrinter class. Switched to StreamOutputPrinter and fixed the issue.

### CODE REVIEW

**Comment by vmztr** [comment]
As this is my first contrib I see that I have a lot of flaws in my commits, I see the travis builds for first time and I suppose phpspec tests should be updated too so please feel free to criticize or send some tips.

Regards

**Comment by elvetemedve** [comment]
Hi @vmztr,

Thanks for contributing.

The best would be to retrieve the OutputPrinter object - used by Behat - from the service container. But as I see there is no such service published. Probably it's intended to be a private class (I guess that's why they removed it without increasing the major version. Semantic versioning failed.). 
So I think replacing the old class with it's successor could be a good solution for now.

You need to switch the `ConsoleOutputPrinter` in the `ScreenshotTakerSpec` class too.
I also see an error in one of the Behat self-testing scenarios here: https://travis-ci.org/elvetemedve/behat-screenshot/jobs/122048590#L418 
Can you check that was well, please?

**Comment by tkotosz** [comment]
@vmztr thanks for contributing!
@elvetemedve The behat tests are working correctly on scrutinizer, so I think thats fine (on travis the behat test fails sometimes randomly, if we rerun the build on travis then I think it will pass). So only the phpspec tests need to be fixed. :)

**Comment by tkotosz** [comment]
@elvetemedve what if we use `Symfony\Component\Console\Output\ConsoleOutput` instead? I think that one should work with both behat 3.0 and 3.1

**Comment by vmztr** [comment]
Hello,

Thank you for you fast responses and great extension. 
@tkotosz  I saw your commit just a moment ago after I pushed the same changes. I also think this is the best approach and it will solve backward compatibility issues like this. With previous solution phpspec tests were failing with `PHP Fatal error: Call to a member function write() on a non-object in Behat/Testwork/Output/Printer/StreamOutputPrinter.php on line 125` I guess I have to mock something but I am still new to phpspec and this will require further debugging from my side. I will be happy to help with any further contributions if I can.

Best Regards

**Comment by elvetemedve** [comment]
@vmztr: Both you and @tkotosz came up with the same solution basically. So it's hard to decide which  solution should I accept. 
I think PR #9 is slightly better, becasue the `symfony/console` component is added as Composer dependency and the more generic `OutputInterface` is used in type hints rather than a specific implementation.

Thank you both.

**Comment by elvetemedve** [comment]
Fix has been released: https://github.com/elvetemedve/behat-screenshot/releases/tag/1.0.7

**Pull request closed without merging**
