### PR TITLE
Added Support for SF5

### PR DESCRIPTION
**Pull request by mnocon**
I've mentioned the lack of support for SF 5 in https://github.com/elvetemedve/behat-screenshot/issues/50

This PR allows to install this extension alongside packages used in Symfony 5.
This is not the only change needed - changes from https://github.com/tkotosz/behat-extension-driver-locator/pull/1 are needed as well.

I've decided to leave the `behat/mink-extension` requirement as it currently is:
if Behat releases a version supporting Symfony 5 no change will be needed, now it works if `friendsOfBehat/MinkExtension` is installed alongisde (FOB replaces the original Behat one: https://github.com/FriendsOfBehat/MinkExtension/blob/v2.4.0/composer.json#L31)

I've tested it locally and it worked for a Symfony 5 project 😄

### CODE REVIEW

**Comment by elvetemedve** [comment]
Nice way of keeping `behat/mink-extension` dependency while having `friendsOfBehat/MinkExtension` installed. These Composer features explains why it is that slow. :D

**Comment by elvetemedve** [comment]
@mnocon Could you update the PHP version to **7.2** (that's the oldest, but still [supported version](https://www.php.net/supported-versions.php)) in `.scrutinizer.yml` as now the build fails due to syntax errors?

**Comment by mnocon** [comment]
Added in https://github.com/elvetemedve/behat-screenshot/pull/51/commits/133e321d4d018fe0215db4654f69fc6ce639412b, it's green 🎉

**Comment by tkotosz** [comment]
@mnocon I mered your PR and released a new major version for the `behat-extension-driver-locator` https://github.com/tkotosz/behat-extension-driver-locator/releases/tag/2.0.0

Coud you please update this PR to require `^2.0`of the `bex/behat-extension-driver-locator`?

**Comment by mnocon** [comment]
Added in https://github.com/elvetemedve/behat-screenshot/commit/c87c883a556563ba4ed6a2185e982a174e8e226d

Travis: https://travis-ci.org/github/elvetemedve/behat-screenshot/builds/672014501 (not sure why it's not listed in checks here on GitHub)

Is passes both on PHP5.x and PHP7.x, installing `bex/behat-extension-driver-locator` if possible:
>   - Installing bex/behat-extension-driver-locator (2.0.0): Cloning 1aa6c5a693 from cache

Looks like PHP 5.4 and 5.5 have been dropped from Travis, should I remove them?

**Comment by tkotosz** [comment]
> not sure why it's not listed in checks here on GitHub

broken (old) webhook config... checking it now

**Comment by tkotosz** [comment]
> Looks like PHP 5.4 and 5.5 have been dropped from Travis, should I remove them?
yes please

**Comment by mnocon** [comment]
Done in https://github.com/elvetemedve/behat-screenshot/pull/51/commits/856facad8a14157c5b8e3a9e4f95ff980428af65 , [Travis build](https://travis-ci.org/github/elvetemedve/behat-screenshot/builds/672020298) is green 😄

**Comment by tkotosz** [comment]
Thank you very much! I am just fixing the 1.x version first, since master is broken atm due to breaking change in behat (https://github.com/elvetemedve/behat-screenshot/pull/52).

Then we can go ahead with this one in 2.x :)

**Comment by elvetemedve** [comment]
@mnocon Thanks for contributing. SF5 support has been released as version [2.1.0](https://github.com/elvetemedve/behat-screenshot/releases/tag/2.1.0).

**Comment by mnocon** [comment]
@elvetemedve @tkotosz Huge thanks to both of you for being helpful and responsive!

**Comment by tkotosz** [comment]
@mnocon np :) let us know if something went wrong and still doesn't work :)

**Pull request merged**
